Repository emacs-vs/docstr, pull requests merged in 2021-04, with the labels that each got.

#9 Fix Some Sentencing in README
  README.md
Labels: documentation

#11 Fix conflict with smartparens
  langs/docstr-python.el
Labels: bug, duplicate

#12 Confirm fix for paring plugins
  langs/docstr-python.el
Labels: bug
